# fontkeep_app/macos/packaging/dmg/make_config.yaml
title: FontKeep
icon: assets/icon/app_icon_512x512.png
contents:
  - x: 448
    y: 344
    type: link
    path: '/Applications'
  - x: 192
    y: 344
    type: file
    path: FontKeep.app